Notes/urls.py
from django.urls import path
from Notes import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.signin, name="login"),
    path("register", views.register, name="register"),
    path("logout", views.signout, name="logout"),
    path("forget-password", views.forget, name="forget"),
    path("continue", views.cont, name="continue"),
    path("home", views.home, name="home"),
    path("theme", views.theme, name="theme"),
    path("base_layout", views.base_layout, name="base"),
]

Notes_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Notes.urls')),
    path('', include('pwa.urls'))
]

Notes/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class User(AbstractUser):
    verified = models.BooleanField(default=False)
    reset = models.BooleanField(default=False)
    photoURL = models.URLField(blank=True, default="")
    themeid = models.IntegerField(default=0)
    pass

Notes/forms.py
from django import forms


class LoginForm(forms.Form):
    Email = forms.EmailField(label="Em@il", widget=forms.EmailInput(
        attrs={'class': "form-control", 'placeholder': 'Email'}))
    Password = forms.CharField(
        label="Password", widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))


class RegisterForm(forms.Form):
    Email = forms.EmailField(label="Em@il", widget=forms.EmailInput(
        attrs={'class': "form-control", 'placeholder': 'Em@il'}))
    Password = forms.CharField(
        label="Password", widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password', 'minlength': 8}))
    Conf_Password = forms.CharField(
        label="Confirm Password", widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}))

Notes/views.py
import json
from django.shortcuts import render
import pyrebase
from Notes.forms import LoginForm, RegisterForm
from Notes.models import User
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.
config = {"data": "Use your own firebase config"}
firebase = pyrebase.initialize_app(config)
fauth = firebase.auth()


def index(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('home'))
    else:
        return render(request, "Notes/index.html")


def base_layout(request):
    return render(request, "Notes/layout.html")


def signin(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data["Email"]
            passwd = form.cleaned_data["Password"]
            try:
                fuser = fauth.sign_in_with_email_and_password(
                    email=email, password=passwd)
                verify = fauth.get_account_info(
                    fuser["idToken"]).get('users')[0].get('emailVerified')
                if verify == False:
                    messages.error(request, "Please verify Email first")
                    return render(request, "Notes/login.html", {
                        "forms": form,
                        "active1": "active"
                    })
                user = User.objects.get(email=email)
                user.verified = verify
                if user.reset == True:
                    user.set_password(passwd)
                    user.reset = False
                user.save()
                user = authenticate(username=user.username, password=passwd)
                login(request, user)
                return HttpResponseRedirect(reverse("home"))
            except Exception as e:
                messages.error(request, "Invalid Credentials")
                return render(request, "Notes/login.html", {
                    "forms": form,
                    "active1": "active"
                })
        else:
            return render(request, "Notes/login.html", {
                "forms": form,
                "active1": "active"
            })
    else:
        return render(request, "Notes/login.html", {
            "forms": LoginForm(),
            "active1": "active"
        })


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data["Email"]
            uname = email[:email.find("@")]
            passwd = form.cleaned_data["Password"]
            conf_pass = form.cleaned_data["Conf_Password"]
            if passwd != conf_pass:
                messages.error(request, "Passwords Doesn't match")
                return render(request, "Notes/register.html", {
                    "forms": form,
                    "active2": "active"
                })
            try:
                user = User.objects.create_user(
                    username=uname, email=email, password=passwd, photoURL="/static/Notes/user.png")
                user.save()
                fuser = fauth.create_user_with_email_and_password(
                    email, passwd)
                fauth.send_email_verification(fuser["idToken"])
                messages.success(
                    request, "An Email is sent to your Email address please verify it to continue login")
                return HttpResponseRedirect(reverse("login"))
            except:
                messages.error(request, "Email Already Exists")
                return render(request, "Notes/register.html", {
                    "forms": form,
                    "active2": "active"
                })
        else:
            return render(request, "Notes/register.html", {
                "forms": form,
                "active2": "active"
            })
    else:
        return render(request, "Notes/register.html", {
            "forms": RegisterForm(),
            "active2": "active"
        })


def signout(request):
    logout(request)
    messages.success(request, "Logout Successful")
    return HttpResponseRedirect(reverse('index'))


def forget(request):
    if request.method == "POST":
        email = request.POST.get("Email", "")
        try:
            user = User.objects.get(email=email)
            user.reset = True
            user.save()
        except User.DoesNotExist:
            messages.error(request, "This email is not registered with us")
            return render(request, "Notes/forget.html")
        fauth.send_password_reset_email(email=email)
        messages.info(request, "Reset link is sent to your email")
        return HttpResponseRedirect(reverse('login'))
    else:
        return render(request, "Notes/forget.html")


def cont(request):
    if request.method == "POST":
        data = request.POST.get("details", "")
        datadict = json.loads(data)
        email = datadict["email"]
        uname = datadict["displayName"]
        verify = datadict["emailVerified"]
        photourl = datadict["photoURL"]
        try:
            user = User.objects.get(email=email)
            user.verified = verify
            user.photoURL = photourl
            user.username = uname
            user.save()
        except User.DoesNotExist:
            user = User.objects.create_user(
                username=uname, email=email, password="", verified=verify, photoURL=photourl)
            user.save()
        user = authenticate(username=user.username, password="")
        login(request, user)
        return HttpResponseRedirect(reverse("home"))
    else:
        return render(request, "Notes/continue.html")


@login_required
def home(request):
    i = 8
    size = []
    while(i <= 72):
        size.append(i)
        if(i >= 12 and i < 28):
            i += 2
        elif(i == 28):
            i += 8
        elif(i == 36):
            i += 12
        elif(i == 48):
            i += 24
        else:
            i += 1
    return render(request, "Notes/home.html", {
        "sizes": size,
    })


@login_required
def theme(request):
    try:
        user = User.objects.get(pk=request.user.pk)
    except User.DoesNotExist:
        return JsonResponse({"error": "User not found"}, status=400)
    if(request.method == "GET"):
        return JsonResponse({"theme": user.themeid}, status=200)
    else:
        data = json.loads(request.body)
        theme = data.get("theme", 0)

        user.themeid = theme
        user.save()
        return JsonResponse({"msg": "Theme setted", "theme": theme}, status=200)

Notes/templates/Notes/continue.html
{% extends "Notes/layout.html" %}
{% load static %}
{% block head %}
<script src="https://www.gstatic.com/firebasejs/8.2.10/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.2.10/firebase-auth.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.2.10/firebase-analytics.js"></script>
<script src="{% static 'Notes/js/config.js' %}"></script>
<script>
    var defPhoto = "{% static 'Notes/user.png' %}";
</script>
<script src="{% static 'Notes/js/after.js' %}"></script>
{% endblock %}
{% block body %}
<div class="logbody">
    <div class="p-4 d-inline-block card box shadow-lg">
        <img src="{% static 'Notes/favicon.png' %}" width=50px alt="notes-logo">
        <br>
        <div id="loader" width=250px height=250px class="text-center m-5">
            <div class="spinner-grow text-danger" style="width: 5rem;height: 5rem;" role="status">
            </div>
        </div>
        <div class="text-center mt-3" id="content" style="display: none;">
            <img id="Photo" class="img-thumbnail" alt="google account image" width=200px style="border-radius:50% ;">
            <h4 class="display-6 text-center">Welcome,<span id="Uname"></span></h4>
            <form method="POST" class="text-center mt-3">
                {% csrf_token %}
                <input type="hidden" name="details" id="account-details">
                <button type="submit" class="btn btn-dark btn-lg">Continue to Homepage</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

Notes/templates/Notes/forget.html
{% extends "Notes/layout.html" %}
{% load static %}
{% block body %}
<div class="logbody">
    <div class="p-4 d-inline-block card box shadow-lg">
        <img src="{% static 'Notes/favicon.png' %}" width=50px>
        <h2 class="text-center">Reset Password</h2>
        <br>
        <form class="mx-auto mt-3" method="POST">
            {% csrf_token %}
            {% include "Notes/message.html" %}
            <div class="form-floating mb-3 mx-3">
                <input type="email" name="Email" class="form-control" placeholder="Em@il" required="" id="id_Email">
                <label for="id_Email">Em@il</label>
            </div>
            <div class="text-center">
                <button class="btn btn-dark mt-2 mx-3 px-4 btn-lg" type="submit">Send Link</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

Notes/templates/Notes/index.html
{% extends 'Notes/layout.html' %}
{% load static %}
{% block body %}
<div class="body">
    <div class="container text-center p-3 disp shadow-lg align-middle">
        <img src="{% static 'Notes/notes-logo.png'%}" class="img-fluid">
        <h1 class="display-3">Welcome to Notes</h1>
        <p class="cursor mb-5" id="Typing"></p>
    </div>

</div>
{% for message in messages %}
<script>
    alert("{{ message| safe}}");
</script>
{% endfor %}
<script>
    var text = "Create, Save and Share.";
    var i = 0;
    var ele = document.getElementById("Typing");
    function type() {
        if (i < text.length) {
            ele.innerHTML += text.charAt(i);
            i++;
            setTimeout(type, 100);
        }
    }
    type();
</script>
{% endblock %}

Notes/templates/Notes/layout.html
{% load static %}
{% load pwa %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Notes</title>
        <link rel="icon" href="{% static 'Notes/favicon.png'%}" sizes="32x32" type="image/ico">
        <link rel="stylesheet" href="{% static 'Notes/css/style.css' %}" type="text/css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
        {% progressive_web_app_meta %}
        {% block head %}
        {% endblock %}
    </head>

    <body>
        <nav class="navbar navbar-dark bg-dark shadow sticky-top">
            <div class="container-fluid">
                <a class="navbar-brand">
                    <img src="{% static 'Notes/favicon_dark.png' %}" width="30" height="30" alt="notes-logo-white" class="d-inline-block align-top">
                    Notes
                </a>
                <div class="end text-end">
                    {% if user.is_authenticated %}
                    <img id="user-image" src="{{user.photoURL}}" class="img-fluid img-thumbnail" width="25px" style="border-radius: 50%;padding: 1px;">
                    <div class="text-white d-inline mx-1 align-middle">{{user.username}}</div>
                    <a class="btn btn-outline-light btn-sm mx-1" href="{% url 'logout' %}">Logout</a>
                    <img src="{% static 'Notes/bars.png' %}" class="img-fluid" width="30px" data-bs-toggle="offcanvas" data-bs-target="#offcanvas" role="button" aria-controls="offcanvas">
                    {% else %}
                    <a class="btn btn-outline-light btn-sm {{active1}}" href="{% url 'login' %}">Sign in</a>&ensp;
                    <a class="btn btn-outline-light btn-sm {{active2}}" href="{% url 'register' %}">Sign up</a>
                    {% endif %}
                </div>
            </div>
        </nav>
        {% block body %}
        {% endblock %}
    </body>

</html>

Notes/templates/Notes/login.html
{% extends "Notes/layout.html" %}
{% load static %}
{% block head %}
<script src="https://www.gstatic.com/firebasejs/8.2.10/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.2.10/firebase-auth.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.2.10/firebase-analytics.js"></script>
<script src="{% static 'Notes/js/config.js' %}"></script>
<script src="https://www.gstatic.com/firebasejs/ui/4.7.3/firebase-ui-auth.js"></script>
<link type="text/css" rel="stylesheet" href="https://www.gstatic.com/firebasejs/ui/4.7.3/firebase-ui-auth.css">
<script>
    var url = "{% url 'continue' %}";
</script>
<script src="{% static 'Notes/js/app.js' %}"></script>
<style>
    .firebaseui-card-footer {
        display: none;
    }

</style>

{% endblock %}
{% block body %}
<div class="logbody">
    <div class="p-4 d-inline-block card box shadow-lg">
        <img src="{% static 'Notes/favicon.png' %}" width=50px>
        <h5 class="display-6 text-center">Welcome Back</h5>
        <br>
        <form class="mx-auto" method="POST">
            {% csrf_token %}
            {% include "Notes/message.html" %}
            {% for form in forms %}
            <div class="form-floating mb-3 mx-3">
                {{form}}
                <label for={{form.id_for_label}}>{{form.label}}</label>
            </div>
            {% endfor %}
            <div class="text-center">
                <div><a href="{% url 'forget' %}" class="d-block link-dark me-3" style="text-align: end;">Forget Password</a></div>
                <button class="btn btn-dark btn-lg my-3 mx-4 px-4" type="submit">Login</button>
                <div class="mt-1">
                    <p class="lead">OR</p>
                    <div id="firebaseui-auth-container"></div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

Notes/templates/Notes/message.html
{% if messages %}
{% for message in messages %}
<div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %} alert-dismissible fade show" role="alert">
    {{message|safe}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}

Notes/templates/Notes/register.html
{% extends "Notes/layout.html" %}
{% load static %}
{% block head %}
<script src="https://www.gstatic.com/firebasejs/8.2.10/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.2.10/firebase-auth.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.2.10/firebase-analytics.js"></script>
<script src="{% static 'Notes/js/config.js' %}"></script>
<script src="https://www.gstatic.com/firebasejs/ui/4.7.3/firebase-ui-auth.js"></script>
<link type="text/css" rel="stylesheet" href="https://www.gstatic.com/firebasejs/ui/4.7.3/firebase-ui-auth.css">
<script>
    var url = "{% url 'continue' %}";
</script>
<script src="{% static 'Notes/js/app.js' %}"></script>
<style>
    .firebaseui-card-footer {
        display: none;
    }

</style>
{% endblock %}
{% block body %}
<div class=" logbody">
    <div class="p-4 d-inline-block card box shadow-lg">
        <img src="{% static 'Notes/favicon.png' %}" width=50px alt="notes-logo">
        <h5 class="display-6 text-center">Welcome to notes</h5>
        <br>
        <form class="mx-auto needs-validation" method="POST">
            {% csrf_token %}
            {% include "Notes/message.html" %}
            {% for form in forms %}
            <div class="form-floating mx-3 mb-3">
                {{form}}
                <label for={{form.id_for_label}}>{{form.label}}</label>
            </div>
            {% endfor %}

            <div class="text-center">
                <button class="btn btn-dark mt-2 mx-3 px-4 btn-lg" type="submit">Register</button>
                <div class="mt-1">
                    <p class="lead">OR</p>
                    <div id="firebaseui-auth-container"></div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}